name: Linux Heilbronn
url: http://linuxheilbronn.github.io
description: Webpräsenz der Linux User Group Heilbronn

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']
