# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Linux User Group Heilbronn
email:

#write html inside the double quotes to display in jumbotron
description: "Gemeinschaft, die sich beruflich oder privat mit dem Betriebssystem Linux/Unix & Derivaten beschäftigt. Treffen: Jeden vierten Donnerstag"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://linuxheilbronn.github.io" # the base hostname & protocol for your site
twitter_username: linuxheilbronn
github_username:  linuxheilbronn

# Build settings
markdown: kramdown
